### ISSUE TITLE
Service integration may not be always necessary (and is difficult to get right regarding non-determinism)

### ISSUE THREAD

**Issue by arothuis-hu** [arothuis-hu/cisq1-lingo#41]
Related: #32

**Comment by arothuis-hu** [comment]
We want to show how to fix non-determism:
* using mocks
* test fixtures in test database (actual PostgresSQL)
* H2 (for example in CI)
* Optional: with test containers

**Comment by rkuijt** [comment]
Not a particular fan of testcontainers. The application should not be responsible for orchestrating infrastructure. H2 would be an exception to this because it mocks the infrastructure in the applications own memory space. Orchestration of other components should be the responsibility of CI.

To use testcontainers, the application will either need to run with elevated privileges or be run as a user within the 'docker' group. Which on most configurations can lead to privilege escalation. This may or may not be mitigated by further hardening but at that point it would make much more sense to use CI deployment configuration to spin up the required containers.

**Comment by arothuis-hu** [comment]
You raise some interesting points! Let's just keep it as-is for now, but I'm going to write up my thought process to document it somewhere for when we reach this point in later years (see context below).

# Course of action

The reason for this issue was two-fold:

1. We want to simplify the CI-setup or, at least, make it more understandable for students
2. We want to offer more control over otherwise non-deterministic integration tests by using test data (fixtures)

Our integration test assignment was a bit too simplistic because we assumed non-determinism. "You can only assert a certain property, not the actual details, i.e. only that a random word to guess is 5 letters long not what the actual word is". Increased determinism makes for more interesting and valuable integration tests and paves the way for controllable end-to-end tests (not sure if we'll add those this year).

I don't think we need to change a lot:

1. Keep using `H2` as an in-memory database for our CI setup, but perhaps name the other options during lectures or assignments
2. Make use of a separate, empty PostgreSQL test database when running integration tests (add `src/test/resources/application.properties` or `src/main/resources/application-test.properties`)
3. Update examples to demonstrate determinism through test fixtures by adding `@BeforeEach` and `@AfterEach` to existing tests

# Context
Testcontainers provide an API to gain control over the environment within a test setup. This simplifies the testing infrastructure considerably (all you need is a container runtime like docker, like in the default `ubuntu` VM in Github Actions). I think in more complicated setups, this is a game changer. For example, [this post](https://engineering.zalando.com/posts/2021/02/integration-tests-with-testcontainers.html) by Zalando's dev team gives a nice write-up.
 
Functionally, it covers the same niche as H2, but offers a slightly more realistic testing environment (i.e. an actual database and possibly other infrastructure, either driven or driver). It also seems to offer per-test control, although that seems rather expensive. Personally, I don't need my infrastructure in a test to be part of the same memory space. Within the context of a CI pipeline logically encapsulation of the system-under-test is reached by packaging within a VM or container. 

I'm not sure about the security risks you mention as I'm not familiar enough with this subject. I have not found anything about the need for hardening a set-up when using testcontainers. That can be a good thing (as in: "it is not necessary") or a bad thing (as in: "everyone assumes the risks to be negligible"). I think the typical justification would be as follows: testcontainers will only be used in a test set-up, are scoped to `test` in `pom.xml` (so it won't be available in a prod or dev context) and it will be run in an isolated CI-container or VM, created and removed per test run. The CI system takes care of docker and user management.

Another alternative to (1) H2 and (2) testcontainers would be, as you said (3) CI-controlled infrastructure, i.e. using [GitHub Actions' services](https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers). We could then use a PostgreSQL container within the CI setup and use a flag (i.e. `-Dspring.profiles.active`) or environment variables to use the correct connection details.
